apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup-workspace
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  steps:
    - name: unit-tests
      image: python:3.9
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        echo "Installing dependencies..."
        pip install -r requirements.txt
        pip install nose

        echo "Running unit tests with nose..."
        nosetests
